version: "3"

volumes:
  videown_mysql_db:
    driver: local
  videown_mysql_cnf:
    driver: local

services:
  mysql:
    image: mysql:8.0.30
    container_name: videown_mysql
    ports:
      - 3306:3306
    volumes:
      - videown_mysql_db:/var/lib/mysql
      - videown_mysql_cnf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    privileged: true
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]